input_folder: /root/bishe/DDM/test/output_0.9/2
output_folder: /root/bishe/video2text/auto_ai_subtitle/mp3_output
srt_folder: /root/bishe/video2text/auto_ai_subtitle/srt_output
from: zh
to: zh
translate_threads: 10
hf_model_path: "/root/bishe/video2text/auto_ai_subtitle/model/whisper-large-v3/pytorch_model.bin"
device: cuda
