# This file is used to read the pkl file generated by the VidEventExtractor.

import pickle

def read_pkl(pkl_file):
    with open(pkl_file, 'rb') as f:
        data = pickle.load(f)
    return data

if __name__ == '__main__':
    pkl_file1 = '/root/bishe/DDM/DDM-Net/DataAssets/multi-frames-GEBD-test-5.pkl'
    pkl_file2 = '/root/bishe/VidEventExtractor/虚假宣传_0.9_submission.pkl'
    data1 = read_pkl(pkl_file1)
    data2 = read_pkl(pkl_file2)
    print(data1)
    print(data2)