# This file is used to read the pkl file generated by the VidEventExtractor.

import pickle

def read_pkl(pkl_file):
    with open(pkl_file, 'rb') as f:
        data = pickle.load(f)
    return data

if __name__ == '__main__':
    pkl_file1 = '/root/bishe/DDM/DataAssets/multi-frames-GEBD-test-5.pkl'
    
    data1 = read_pkl(pkl_file1)
    
    print(data1)
    